language: python
python:
    - "3.6"

env:
  - POSTGRES_PASSWORD=postgres
  - PATTON_HTTP_PORT=8000
  - PATTON_HTTP_WORKERS=1

services:
  - postgresql
  - docker

# command to install dependencies
#install: "make"

#addons:
#  apt:
#    packages:
#      - libenchant-dev

# command to run tests
#script:
#    - make lint test-coverage codecov

deploy:

  # Deploy to PyPI
  - provider: pypi
    user: $PYPI_USER
    password: $PYPI_PASSWD
    distributions: "sdist"
    skip_cleanup: true
    on:
      branch: tag
