language: python
python:
    - "3.6"

deploy:

  - provider: script
    execute: make upload-pypi
    on:
      branch: tag

  - provider: script
    execute: make upload-docker
    on:
      branch: tag
