---
version: "3"

services:

  patton:
    image: ${BUILD_IMAGE}
    env_file: ${ENV:-.env}
    depends_on:
     - redis
     - postgres

  postgres:
    image: postgres:latest
    env_file: ${ENV:-.env}
    restart: "always"
    ports:
      - "5432:5432"

  redis:
    image: redis:4.0
    env_file: ${ENV:-.env}
    ports:
      - "6379:6379"

