version: 2
jobs:
  build:
    docker:
      - image: cr0hn/python3.6-alpine-make:1.0.4

    working_directory: ~/repo

    branches:
      only:
        - master

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 17.07.0-ce

      - deploy:
          name: Upload patton-server to pypi
          working_directory: server
          command: make upload-pypi

      - deploy:
          name: Upload patton-client to pypi
          working_directory: client
          command: make upload-pypi

      - deploy:
          name: Upload patton-server to Dockerhub
          working_directory: server
          command: make upload-docker

      - deploy:
          name: Upload patton-client to Dockerhub
          working_directory: client
          command: make upload-docker
