version: 2
jobs:
  build:
    docker:
      - image: cr0hn/python3.6-alpine-make:1.0.4

    working_directory: ~/repo

    branches:
      only:
        - refactor_patton_project

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 17.07.0-ce

      - run:
          name: Upload to pypi
          working_directory: server
          command: cat make

      - run:
          name: Upload to pypi
          working_directory: client
          command: cat make

      - run:
          name: Upload to Dockerhub
          working_directory: server
          command: cat make

      - run:
          name: Upload to Dockerhub
          working_directory: client
          command: cat make
