name: Cook CVE database and publish it

on:
  schedule:
    - cron:  '0 11 * * *'
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone current repo
      uses: actions/checkout@v2
      with:
        ref: develop

    - name: Install zstd compressor
      run: |
        sudo apt update
        sudo apt install zstd

    - name: Setup go 1.14
      id: go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - name: Setup godog
      run: go get -v github.com/cucumber/godog/cmd/godog@v0.8.0
      env:
        GO111MODULE: on

    - name: Run make
      run: make -j8 -l2

    - name: Verify acceptance tests
      run: |
        cd acceptance
        ~/go/bin/godog
      env:
        PATTON_BINARY: ../bin/patton
        PATTON_DATABASE: ../patton.db.zst

    - name: Delete release with hub
      shell: bash
      run: |
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        bin/hub release --include-drafts | grep latest && bin/hub release delete latest || true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Obtain current date
      id: current-date
      run: |
        echo ::set-output name=date::$(date +%Y%m%d)

    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest
        release_name: Release ${{ steps.current-date.outputs.date }}
        body: |
          Daily release (experimental)

          The last stable release can be obtained here:
          https://github.com/BBVA/patton/releases/tag/v0.0.4
        draft: true
        prerelease: true

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./patton.db.zst
        asset_name: patton.db.zst
        asset_content_type: application/zstd
